seed: 219

increment_cons: p0.5
initial_size: p0.5

generator: True
method: pap 

main_directory: /cta/users/aosman/alNER/
data_directory: /cta/users/aosman/alNER//datasets/tokenized/

data_set:
  name: CONLL2003
  pos: True

pretrained_model: bert-base-cased

#sl4l
#ll
#cl4l
embedding_type: ll

init_reduction:
  type: pca
  pca:
    dimension: 300
  umap:
    dimension: 300
    min_dist: 0.0
    neig: 40

CRF:
  algorithm: lbfgs
  c1: 0.1
  c2: 0.1
  max_iterations: 100
  allow_all_states: True
  allow_all_transitions: True

hdbscan_al:
  mask_outlier: 0.99
  min_c_size: 1000
  min_samp: 200
  c_eps: 0.17

umap_al:
  neig: 40
  min_dist: 0.0
  n_comp: 2

