seed: 219

increment_cons: p10
initial_size: p10

generator: True
method: rs 

main_directory: /cta/users/aosman/alNER/
data_directory: /cta/users/aosman/alNER/datasets/tokenized/

data_set:
  name: CONLL2003
  pos: False

#"bert-base-cased"
#"monologg/biobert_v1.1_pubmed"
#"emilyalsentzer/Bio_ClinicalBERT"
#"microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
#"monologg/biobert_v1.1_pubmed"
pretrained_model: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
#sl4l
#ll
#cl4l
embedding_type: sl4l

init_reduction:
  type: pca
  pca:
    dimension: 256
  umap:
    dimension: 200
    min_dist: 0.0
    neig: 40

CRF:
  algorithm: lbfgs
  c1: 0.1
  c2: 0.1
  max_iterations: 100
  allow_all_states: True
  allow_all_transitions: True

hdbscan_al:
  mask_outlier: 0.99
  min_c_size: 1000
  min_samp: 200
  c_eps: 0.2

umap_al:
  neig: 40
  min_dist: 0.0
  n_comp: 2
